"""
Page 1 — Daily Brief
Portfolio overview, movers, unified news summary, macro alerts, signals, sources.
"""
import asyncio

import streamlit as st

from brief import generate_daily_brief
from data.firestore_client import get_todays_brief
from utils.nav import render_nav
from utils.ui_components import (
    macro_card,
    section_header,
    sentiment_badge,
    signal_badge,
)

st.set_page_config(page_title="Daily Brief | MarketMind", layout="wide")

# ── Auth gate ─────────────────────────────────────────────────────────────────

uid = st.session_state.get("uid")
if not uid:
    st.switch_page("app.py")
    st.stop()

render_nav()

st.title("Daily Brief")

# ── Load / Generate ───────────────────────────────────────────────────────────

brief = get_todays_brief(uid)

col_refresh, _ = st.columns([1, 5])
with col_refresh:
    if st.button("Generate Today's Brief", type="primary"):
        brief = None  # force regeneration

if brief is None:
    with st.status("Generating your daily brief...", expanded=True) as status:
        st.write("Fetching latest news and computing portfolio...")
        brief = asyncio.run(generate_daily_brief(uid))
        st.write("Brief complete.")
        status.update(label="Daily brief ready!", state="complete")

if brief.get("empty"):
    st.info(brief["message"])
    st.stop()

snapshot = brief.get("portfolio_snapshot", {})
holdings = snapshot.get("holdings", [])
total_market  = snapshot.get("total_market_value", 0)
total_pnl     = snapshot.get("total_pnl", 0)
total_pnl_pct = snapshot.get("total_pnl_pct", 0)

# Approximate portfolio daily P&L from per-holding data
daily_pnl     = sum(h.get("market_value", 0) * h.get("daily_pct", 0) / 100 for h in holdings)
daily_pnl_pct = daily_pnl / total_market * 100 if total_market else 0.0

# ── Section 1 — Portfolio Overview ───────────────────────────────────────────

st.markdown(section_header("Portfolio Overview"), unsafe_allow_html=True)
col1, col2, col3 = st.columns(3)
col1.metric("Total Value",  f"${total_market:,.2f}")
col2.metric("Today",        f"${daily_pnl:+,.2f}",  f"{daily_pnl_pct:+.2f}%")
col3.metric("Total P&L",    f"${total_pnl:+,.2f}",  f"{total_pnl_pct:+.2f}%")

st.markdown("<br>", unsafe_allow_html=True)

col_btn, col_spacer = st.columns([1, 4])
with col_btn:
    if st.button("▶  Listen to Brief", use_container_width=True):
        with st.spinner("Generating audio brief..."):
            try:
                from brief.audio_brief import generate_audio_brief
                audio_bytes = generate_audio_brief(brief)
                st.session_state["audio_brief"] = audio_bytes
            except Exception as e:
                st.error(f"Audio generation failed: {e}")

if "audio_brief" in st.session_state:
    st.audio(st.session_state["audio_brief"], format="audio/mp3")
    st.caption(
        "🎙 MarketMind Daily Brief · Generated by OpenAI TTS · "
        "Not financial advice"
    )

# ── Section 2 — Today's Movers ────────────────────────────────────────────────

if holdings:
    st.markdown(section_header("Today's Movers"), unsafe_allow_html=True)
    sorted_holdings = sorted(holdings, key=lambda x: abs(x.get("daily_pct", 0)), reverse=True)
    cols = st.columns(min(len(sorted_holdings), 5))
    for i, h in enumerate(sorted_holdings):
        cols[i % 5].metric(
            label=h["ticker"],
            value=f"${h['current_price']:.2f}",
            delta=f"{h['daily_pct']:+.2f}%",
        )

st.markdown("---")

# ── Section 3 — Portfolio News Summary ───────────────────────────────────────

st.markdown(section_header("Portfolio Summary"), unsafe_allow_html=True)
summary_data = brief.get("portfolio_summary", {})
summary_text = summary_data.get("summary", "Summary unavailable.")
label        = summary_data.get("sentiment_label", "neutral")
score        = float(summary_data.get("sentiment_score", 5.0))

st.markdown(
    f"<p style='font-size:16px;line-height:1.9;color:#ffffff;"
    f"background:#0a0a0a;padding:20px;border-radius:10px;"
    f"border-left:3px solid #76b900;font-family:Inter,sans-serif'>"
    f"{summary_text}</p>",
    unsafe_allow_html=True,
)
st.markdown(
    sentiment_badge(label) +
    f"<span style='color:#52525b;font-size:13px;margin-left:10px;"
    f"font-family:Inter,sans-serif'>Sentiment {score:.1f}/10</span>",
    unsafe_allow_html=True,
)

st.markdown("---")

# ── Section 4 — Global Headlines ─────────────────────────────────────────────

st.markdown(section_header("Global Headlines to Watch"), unsafe_allow_html=True)
macro = brief.get("macro_alerts", [])
if not macro:
    st.caption("No significant macro events detected for your portfolio today.")
else:
    for m in macro:
        st.markdown(
            macro_card(
                headline    = m.get("headline", ""),
                why_matters = m.get("why_matters", ""),
                impact      = m.get("impact", "neutral"),
                score       = m.get("relevance_score", 0),
                source      = m.get("source_name", ""),
                url         = m.get("url") or "",
            ),
            unsafe_allow_html=True,
        )

st.markdown("---")

# ── Buy / Wait / Sell Signals ─────────────────────────────────────────────────

st.markdown(section_header("Signals"), unsafe_allow_html=True)
signals = brief.get("signals", {})
if signals:
    for ticker, sig in signals.items():
        signal_val = sig.get("signal", "WAIT")
        urgency    = sig.get("urgency", "LOW")
        st.markdown(
            f"{signal_badge(signal_val)}"
            f" &nbsp; <span style='color:#ffffff;font-weight:600;"
            f"font-family:Inter,sans-serif'>{ticker}</span>"
            f" &nbsp; <code>{urgency}</code>"
            f" &nbsp; <span style='color:#a1a1aa;"
            f"font-family:Inter,sans-serif'>— {sig.get('reason', '')}</span>",
            unsafe_allow_html=True,
        )
        if sig.get("watch_price"):
            st.caption(f"Watch price: ${sig['watch_price']:.2f}")
else:
    st.caption("No signals generated.")

st.markdown("---")

# ── Section 5 — Source Links ─────────────────────────────────────────────────

st.markdown(section_header("Further Reading"), unsafe_allow_html=True)
sources = brief.get("sources", [])
if not sources:
    st.caption("No source links available.")
else:
    for s in sources:
        ticker   = s.get("ticker", "")
        headline = s.get("headline", "")[:80]
        url      = s.get("url", "")
        domain   = s.get("domain", "")
        pub      = s.get("published_at", "")
        st.markdown(
            f"<div style='margin-bottom:6px'>"
            f"<span style='font-size:11px;color:#76b900;font-weight:600;"
            f"font-family:Inter,sans-serif'>{ticker}</span> "
            f"<a href='{url}' style='color:#ffffff;font-size:13px;"
            f"font-family:Inter,sans-serif'>{headline}...</a> "
            f"<span style='color:#52525b;font-size:11px;"
            f"font-family:Inter,sans-serif'>· {domain} · {pub}</span>"
            f"</div>",
            unsafe_allow_html=True,
        )

generated_at = brief.get("generated_at", "")
if generated_at:
    st.caption(f"Generated at {generated_at} UTC")
