"""
Page 1 — Daily Brief
Portfolio overview, movers, unified news summary, macro alerts, signals, sources.
"""
import asyncio
import base64

import streamlit as st
import streamlit.components.v1 as components

from brief import generate_daily_brief
from data.firestore_client import delete_todays_brief, get_todays_brief
from utils.nav import render_nav
from utils.ui_components import (
    macro_card,
    section_header,
    sentiment_badge,
    signal_badge,
)

st.set_page_config(page_title="Daily Brief | MarketMind", layout="wide")

# ── Auth gate ─────────────────────────────────────────────────────────────────

uid = st.session_state.get("uid")
if not uid:
    st.switch_page("app.py")
    st.stop()

render_nav()

# ── Scrolling disclaimer ticker ───────────────────────────────────────────────
st.markdown("""
<style>
#mm-ticker-wrap {
    position: fixed;
    bottom: 0;
    left: 0;
    width: 100%;
    z-index: 9999;
    background: #f5c518;
    border-top: 1px solid #d4a800;
    overflow: hidden;
    height: 32px;
    display: flex;
    align-items: center;
}
#mm-ticker-track {
    display: flex;
    white-space: nowrap;
    animation: mm-scroll 60s linear infinite;
}
#mm-ticker-track:hover {
    animation-play-state: paused;
}
.mm-ticker-inner {
    display: inline-block;
    padding-right: 80px;
    font-family: 'Inter', sans-serif;
    font-size: 12px;
    font-weight: 600;
    color: #000000;
    letter-spacing: 0.02em;
}
.mm-ticker-sep {
    color: #7a6000;
    padding: 0 10px;
}
@keyframes mm-scroll {
    0%   { transform: translateX(0); }
    100% { transform: translateX(-50%); }
}
</style>
<div id="mm-ticker-wrap">
  <div id="mm-ticker-track">
    <span class="mm-ticker-inner">
      &nbsp;&nbsp;
      <b>SIGNAL GUIDE</b>
      <span class="mm-ticker-sep">|</span>
      <b>BUY</b> — Analyst conditions favour entering or adding to a position
      <span class="mm-ticker-sep">•</span>
      <b>WAIT</b> — Hold current position; no strong catalyst yet
      <span class="mm-ticker-sep">•</span>
      <b>SELL</b> — Consider reducing or exiting exposure
      <span class="mm-ticker-sep">|</span>
      <b>URGENCY:</b>
      <span class="mm-ticker-sep">•</span>
      <b>HIGH</b> — Imminent catalyst (earnings, Fed, breaking news) — act soon
      <span class="mm-ticker-sep">•</span>
      <b>MEDIUM</b> — Monitor over the next few days
      <span class="mm-ticker-sep">•</span>
      <b>LOW</b> — No near-term catalyst; longer-term view
      <span class="mm-ticker-sep">|</span>
      ⚠ <b>DISCLAIMER:</b> This analysis is generated by AI and may contain errors.
      MarketMind is <b>not a registered investment advisor</b>.
      Nothing here constitutes financial advice.
      Always read the source news articles for further background before making any investment decision.
      Past performance does not guarantee future results.
      <span class="mm-ticker-sep">|</span>
    </span>
    <!-- duplicate for seamless loop -->
    <span class="mm-ticker-inner">
      &nbsp;&nbsp;
      <b>SIGNAL GUIDE</b>
      <span class="mm-ticker-sep">|</span>
      <b>BUY</b> — Analyst conditions favour entering or adding to a position
      <span class="mm-ticker-sep">•</span>
      <b>WAIT</b> — Hold current position; no strong catalyst yet
      <span class="mm-ticker-sep">•</span>
      <b>SELL</b> — Consider reducing or exiting exposure
      <span class="mm-ticker-sep">|</span>
      <b>URGENCY:</b>
      <span class="mm-ticker-sep">•</span>
      <b>HIGH</b> — Imminent catalyst (earnings, Fed, breaking news) — act soon
      <span class="mm-ticker-sep">•</span>
      <b>MEDIUM</b> — Monitor over the next few days
      <span class="mm-ticker-sep">•</span>
      <b>LOW</b> — No near-term catalyst; longer-term view
      <span class="mm-ticker-sep">|</span>
      ⚠ <b>DISCLAIMER:</b> This analysis is generated by AI and may contain errors.
      MarketMind is <b>not a registered investment advisor</b>.
      Nothing here constitutes financial advice.
      Always read the source news articles for further background before making any investment decision.
      Past performance does not guarantee future results.
      <span class="mm-ticker-sep">|</span>
    </span>
  </div>
</div>
""", unsafe_allow_html=True)

st.title("Daily Brief")

# ── Load / Generate ───────────────────────────────────────────────────────────

brief = get_todays_brief(uid)

col_refresh, _ = st.columns([1, 5])
with col_refresh:
    if st.button("Generate Today's Brief", type="primary"):
        delete_todays_brief(uid)   # clear cache so new portfolio stocks are included
        brief = None

if brief is None:
    with st.status("Generating your daily brief...", expanded=True) as status:
        st.write("Fetching latest news and computing portfolio...")
        brief = asyncio.run(generate_daily_brief(uid))
        st.write("Brief complete.")
        status.update(label="Daily brief ready!", state="complete")

if brief.get("empty"):
    st.info(brief["message"])
    st.stop()

snapshot = brief.get("portfolio_snapshot", {})
holdings = snapshot.get("holdings", [])
total_market  = snapshot.get("total_market_value", 0)
total_pnl     = snapshot.get("total_pnl", 0)
total_pnl_pct = snapshot.get("total_pnl_pct", 0)

# Approximate portfolio daily P&L from per-holding data
daily_pnl     = sum(h.get("market_value", 0) * h.get("daily_pct", 0) / 100 for h in holdings)
daily_pnl_pct = daily_pnl / total_market * 100 if total_market else 0.0

# ── Section 1 — Portfolio Overview ───────────────────────────────────────────

st.markdown(section_header("Portfolio Overview"), unsafe_allow_html=True)
col1, col2, col3 = st.columns(3)
col1.metric("Total Value",  f"${total_market:,.2f}")
col2.metric("Today",        f"${daily_pnl:+,.2f}",  f"{daily_pnl_pct:+.2f}%")
col3.metric("Total P&L",    f"${total_pnl:+,.2f}",  f"{total_pnl_pct:+.2f}%")

st.markdown("<br>", unsafe_allow_html=True)

col_btn, col_spacer = st.columns([1, 4])
with col_btn:
    if st.button("▶  Listen to Brief", use_container_width=True):
        with st.spinner("Generating audio brief..."):
            try:
                from brief.audio_brief import generate_audio_brief
                audio_bytes = generate_audio_brief(brief)
                st.session_state["audio_brief"] = audio_bytes
            except Exception as e:
                st.error(f"Audio generation failed: {e}")

if "audio_brief" in st.session_state:
    audio_b64 = base64.b64encode(st.session_state["audio_brief"]).decode()
    components.html(f"""
    <style>
      * {{ box-sizing: border-box; margin: 0; padding: 0; font-family: 'Inter', sans-serif; }}
      body {{ background: transparent; }}
      #player {{
        background: #0a0a0a;
        border: 1px solid #1a1a1a;
        border-radius: 12px;
        padding: 16px 20px;
        display: flex;
        flex-direction: column;
        gap: 12px;
      }}
      #topRow {{
        display: flex;
        align-items: center;
        gap: 14px;
      }}
      #playBtn {{
        background: #76b900;
        color: #000;
        border: none;
        border-radius: 50%;
        width: 40px;
        height: 40px;
        font-size: 16px;
        cursor: pointer;
        flex-shrink: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        transition: background 0.2s;
      }}
      #playBtn:hover {{ background: #8fd400; }}
      #trackInfo {{
        flex: 1;
      }}
      #trackTitle {{
        color: #ffffff;
        font-size: 13px;
        font-weight: 600;
        letter-spacing: 0.01em;
      }}
      #trackSub {{
        color: #52525b;
        font-size: 11px;
        margin-top: 2px;
      }}
      #timeDisplay {{
        color: #a1a1aa;
        font-size: 12px;
        font-variant-numeric: tabular-nums;
        white-space: nowrap;
      }}
      #waveCanvas {{
        width: 100%;
        height: 60px;
        border-radius: 6px;
        display: block;
      }}
      #progressRow {{
        display: flex;
        align-items: center;
        gap: 8px;
      }}
      #progressBar {{
        flex: 1;
        height: 3px;
        background: #1a1a1a;
        border-radius: 2px;
        cursor: pointer;
        position: relative;
      }}
      #progressFill {{
        height: 100%;
        background: #76b900;
        border-radius: 2px;
        width: 0%;
        transition: width 0.1s linear;
      }}
    </style>

    <div id="player">
      <div id="topRow">
        <button id="playBtn">&#9654;</button>
        <div id="trackInfo">
          <div id="trackTitle">MarketMind Daily Brief</div>
          <div id="trackSub">Generated by OpenAI TTS &middot; Not financial advice</div>
        </div>
        <div id="timeDisplay">0:00 / 0:00</div>
      </div>
      <canvas id="waveCanvas"></canvas>
      <div id="progressRow">
        <div id="progressBar"><div id="progressFill"></div></div>
      </div>
    </div>

    <audio id="audioEl" src="data:audio/mp3;base64,{audio_b64}" preload="auto"></audio>

    <script>
      const audio    = document.getElementById('audioEl');
      const canvas   = document.getElementById('waveCanvas');
      const btn      = document.getElementById('playBtn');
      const timeLbl  = document.getElementById('timeDisplay');
      const progFill = document.getElementById('progressFill');
      const progBar  = document.getElementById('progressBar');
      const c        = canvas.getContext('2d');

      // Resize canvas to match CSS display size
      function resizeCanvas() {{
        canvas.width  = canvas.offsetWidth  * window.devicePixelRatio;
        canvas.height = canvas.offsetHeight * window.devicePixelRatio;
        c.scale(window.devicePixelRatio, window.devicePixelRatio);
      }}
      resizeCanvas();
      window.addEventListener('resize', resizeCanvas);

      let audioCtx, analyser, source, animId;
      let isPlaying = false;

      function fmt(s) {{
        const m = Math.floor(s / 60);
        const ss = Math.floor(s % 60).toString().padStart(2, '0');
        return m + ':' + ss;
      }}

      audio.addEventListener('loadedmetadata', () => {{
        timeLbl.textContent = '0:00 / ' + fmt(audio.duration);
      }});

      audio.addEventListener('timeupdate', () => {{
        if (!audio.duration) return;
        const pct = (audio.currentTime / audio.duration) * 100;
        progFill.style.width = pct + '%';
        timeLbl.textContent = fmt(audio.currentTime) + ' / ' + fmt(audio.duration);
      }});

      audio.addEventListener('ended', () => {{
        isPlaying = false;
        btn.innerHTML = '&#9654;';
        cancelAnimationFrame(animId);
        drawIdle();
      }});

      progBar.addEventListener('click', (e) => {{
        if (!audio.duration) return;
        const rect = progBar.getBoundingClientRect();
        const pct  = (e.clientX - rect.left) / rect.width;
        audio.currentTime = pct * audio.duration;
      }});

      btn.addEventListener('click', async () => {{
        if (!audioCtx) {{
          audioCtx = new AudioContext();
          analyser = audioCtx.createAnalyser();
          analyser.fftSize = 128;
          analyser.smoothingTimeConstant = 0.8;
          source = audioCtx.createMediaElementSource(audio);
          source.connect(analyser);
          analyser.connect(audioCtx.destination);
        }}
        if (audioCtx.state === 'suspended') await audioCtx.resume();

        if (isPlaying) {{
          audio.pause();
          isPlaying = false;
          btn.innerHTML = '&#9654;';
          cancelAnimationFrame(animId);
        }} else {{
          audio.play();
          isPlaying = true;
          btn.innerHTML = '&#9646;&#9646;';
          drawLive();
        }}
      }});

      function drawIdle() {{
        const W = canvas.offsetWidth;
        const H = canvas.offsetHeight;
        c.clearRect(0, 0, W, H);
        const bars = 48;
        const gap  = 2;
        const bw   = (W - gap * (bars - 1)) / bars;
        for (let i = 0; i < bars; i++) {{
          const x = i * (bw + gap);
          const h = 2;
          c.fillStyle = 'rgba(118,185,0,0.25)';
          c.beginPath();
          c.roundRect(x, H / 2 - h / 2, bw, h, 1);
          c.fill();
        }}
      }}

      function drawLive() {{
        animId = requestAnimationFrame(drawLive);
        const W = canvas.offsetWidth;
        const H = canvas.offsetHeight;
        c.clearRect(0, 0, W, H);

        const bufLen = analyser.frequencyBinCount;
        const data   = new Uint8Array(bufLen);
        analyser.getByteFrequencyData(data);

        const bars = 48;
        const gap  = 2;
        const bw   = (W - gap * (bars - 1)) / bars;
        const step = Math.floor(bufLen / bars);

        for (let i = 0; i < bars; i++) {{
          const val = data[i * step] / 255;
          const bh  = Math.max(3, val * H * 0.9);
          const x   = i * (bw + gap);
          const y   = (H - bh) / 2;

          const grad = c.createLinearGradient(0, y, 0, y + bh);
          grad.addColorStop(0, '#8fd400');
          grad.addColorStop(0.5, '#76b900');
          grad.addColorStop(1, 'rgba(118,185,0,0.4)');

          c.fillStyle = grad;
          c.beginPath();
          c.roundRect(x, y, bw, bh, 2);
          c.fill();
        }}
      }}

      // Draw idle state on load
      window.addEventListener('load', drawIdle);
      setTimeout(drawIdle, 100);
    </script>
    """, height=175)

# ── Section 2 — Today's Movers ────────────────────────────────────────────────

if holdings:
    st.markdown(section_header("Today's Movers"), unsafe_allow_html=True)
    sorted_holdings = sorted(holdings, key=lambda x: abs(x.get("daily_pct", 0)), reverse=True)
    cols = st.columns(min(len(sorted_holdings), 5))
    for i, h in enumerate(sorted_holdings):
        cols[i % 5].metric(
            label=h["ticker"],
            value=f"${h['current_price']:.2f}",
            delta=f"{h['daily_pct']:+.2f}%",
        )

st.markdown("---")

# ── Section 3 — Portfolio News Summary ───────────────────────────────────────

st.markdown(section_header("Portfolio Summary"), unsafe_allow_html=True)
summary_data = brief.get("portfolio_summary", {})
summary_text = summary_data.get("summary", "Summary unavailable.")
label        = summary_data.get("sentiment_label", "neutral")
score        = float(summary_data.get("sentiment_score", 5.0))

st.markdown(
    f"<p style='font-size:16px;line-height:1.9;color:#ffffff;"
    f"background:#0a0a0a;padding:20px;border-radius:10px;"
    f"border-left:3px solid #76b900;font-family:Inter,sans-serif'>"
    f"{summary_text}</p>",
    unsafe_allow_html=True,
)
st.markdown(
    sentiment_badge(label) +
    f"<span style='color:#52525b;font-size:13px;margin-left:10px;"
    f"font-family:Inter,sans-serif'>Sentiment {score:.1f}/10</span>",
    unsafe_allow_html=True,
)

st.markdown("---")

# ── Section 4 — Global Headlines ─────────────────────────────────────────────

st.markdown(section_header("Global Headlines to Watch"), unsafe_allow_html=True)
macro = brief.get("macro_alerts", [])
if not macro:
    st.caption("No significant macro events detected for your portfolio today.")
else:
    for m in macro:
        st.markdown(
            macro_card(
                headline    = m.get("headline", ""),
                why_matters = m.get("why_matters", ""),
                impact      = m.get("impact", "neutral"),
                score       = m.get("relevance_score", 0),
                source      = m.get("source_name", ""),
                url         = m.get("url") or "",
            ),
            unsafe_allow_html=True,
        )

st.markdown("---")

# ── Buy / Wait / Sell Signals ─────────────────────────────────────────────────

st.markdown(section_header("Signals"), unsafe_allow_html=True)
signals = brief.get("signals", {})
if signals:
    for ticker, sig in signals.items():
        signal_val = sig.get("signal", "WAIT")
        urgency    = sig.get("urgency", "LOW")
        st.markdown(
            f"{signal_badge(signal_val)}"
            f" &nbsp; <span style='color:#ffffff;font-weight:600;"
            f"font-family:Inter,sans-serif'>{ticker}</span>"
            f" &nbsp; <code>{urgency}</code>"
            f" &nbsp; <span style='color:#a1a1aa;"
            f"font-family:Inter,sans-serif'>— {sig.get('reason', '')}</span>",
            unsafe_allow_html=True,
        )
        if sig.get("watch_price"):
            st.caption(f"Watch price: ${sig['watch_price']:.2f}")
else:
    st.caption("No signals generated.")

st.markdown("---")

# ── Section 5 — Source Links ─────────────────────────────────────────────────

st.markdown(section_header("Further Reading"), unsafe_allow_html=True)
sources = brief.get("sources", [])
if not sources:
    st.caption("No source links available.")
else:
    for s in sources:
        ticker   = s.get("ticker", "")
        headline = s.get("headline", "")[:80]
        url      = s.get("url", "")
        domain   = s.get("domain", "")
        pub      = s.get("published_at", "")
        st.markdown(
            f"<div style='margin-bottom:6px'>"
            f"<span style='font-size:11px;color:#76b900;font-weight:600;"
            f"font-family:Inter,sans-serif'>{ticker}</span> "
            f"<a href='{url}' style='color:#ffffff;font-size:13px;"
            f"font-family:Inter,sans-serif'>{headline}...</a> "
            f"<span style='color:#52525b;font-size:11px;"
            f"font-family:Inter,sans-serif'>· {domain} · {pub}</span>"
            f"</div>",
            unsafe_allow_html=True,
        )

generated_at = brief.get("generated_at", "")
if generated_at:
    st.caption(f"Generated at {generated_at} UTC")
